package project.Lexer;

enum TokenType {
        PROGRAM, RESULT, IF, INTCONSTANT, COMMA, LEFTBRACKET,
        BEGIN, THEN, REALCONSTANT, SEMICOLON, RIGHTBRACKET,
        END, REAL, ELSE, RELOP, COLON, UNARYMINUS,
        VAR, ARRAY, WHILE, MULOP, LEFTPAREN, UNARYPLUS,
        FUNCTION, OF, DO, ADDOP, RIGHTPAREN, ENDMARKER,
        PROCEDURE, NOT, IDENTIFIER, ASSIGNOP, DOUBLEDOT, ENDOFFILE,
 }
